# utils/locales/zh_tw.py
# -*- coding: utf-8 -*-

STRINGS = {
    # --- [New] On-Premise / Institutional Branding ---
    #Spotlight
    "adv_latex_title": "LATEX 高精準解析",
    "adv_latex_desc": "深度識別複雜數學公式與科學符號，專為 STEM 教育設計。",
    "adv_grading_title": "混合式智能閱卷",
    "adv_grading_desc": "結合教師專業判斷與 AI 輔助評分，大幅提升批改效率。",
    "adv_quota_title": "自定義配額管理",
    "adv_quota_desc": "根據機構需求靈活分配資源，確保系統運行穩健。",
    "badge_exclusive_license": "機構專屬授權",
    "desc_secure_grading": "專為學術研究與專業評分打造的受控環境",
    "stat_connected": "已連線",
    "stat_protected": "受保護",
    "lbl_net_status": "網路狀態",
    "lbl_privacy": "隱私層級",
    "lbl_quota": "使用配額",
    "lbl_version": "引擎版本",
    "lbl_sys_info": "系統資訊",
    "msg_licensed_to": "軟體授權歸屬於",
    "lbl_deploy_mode": "部署模式",
    # --- Common / Global ---
    "app_name": "AI 智慧閱卷工作平台",
    "badge_recommended": "專業首選",
    "title": "🎓 AI 智慧閱卷工作台",
    "logout": "登出",
    "action_fail": "操作失敗",
    "welcome": "歡迎，{}",
    "subj_math": "數學",
    "subj_physics": "物理",
    "subj_chemistry": "化學",
    "subj_coding": "程式設計",
    "subj_essay": "申論寫作",
    # --- Exam Gen Metadata & Actions ---
    "lbl_academic_year": "學年度",
    "lbl_grade_level": "適用年級",
    "opt_freshman": "大一",
    "opt_sophomore": "大二",
    "opt_junior": "大三",
    "opt_senior": "大四",
    "opt_grad": "研究所",
    "lbl_current_q_count": "目前題目數量: {}",
    "btn_gen_preview_free": "👁️ 生成預覽 PDF (不扣點)",
    "btn_finalize_deduct": "🚀 定稿並歸檔 (扣 1 點)",
    "btn_download_preview": "📥 下載預覽 PDF",
    "btn_download_final": "📥 下載正式考卷 PDF",
    "btn_load_edit": "載入編輯",
    "btn_clone_exam": "建立副本 (Clone)",
    "msg_preview_ok": "預覽生成成功！(浮水印 DRAFT)",
    "msg_finalize_ok": "✅ 定稿成功！配額已扣除 (1)。",
    "msg_gen_fail": "生成失敗，請檢查 LaTeX 語法。",
    "msg_quota_fail": "❌ 配額不足：{}",
    "msg_no_records": "尚無試卷紀錄。",
    "msg_loaded_ok": "已載入！請切換至「試卷生成」分頁。",
    "msg_cloned_ok": "已建立副本！請切換至「試卷生成」分頁修改。",
    "mode_creator": "出卷中心",
    "mode_grader": "閱卷中心",
    "switch_mode": "切換工作模式",
    "menu_header_creator": "試卷設計與管理",
    "menu_header_grader": "作業批改與分析",
    "menu_subscription": "訂閱方案",
    "menu_exam_gen": "試卷生成",
    "menu_grading": "開始閱卷",
    "menu_my_exams": "我的試卷庫",
    "menu_history": "歷史紀錄",
    "menu_admin": "系統管理",
    "menu_settings": "個人設定",
    "menu_solution": "解答編輯",
    "menu_bank": "智慧題庫中心",
    "menu_public_bank": "公開題庫",
    "tab_login": "登入 (Login)",
    "tab_register": "註冊 (Register)",
    "header_welcome": "歡迎回來",
    "lbl_username": "帳號 (Username)",
    "lbl_password": "密碼 (Password)",
    "btn_signin": "登入",
    "btn_signup": "送出註冊申請",
    "msg_validating": "驗證中...",
    "msg_welcome_user": "歡迎, {}!",
    "err_login_fail": "登入失敗：帳號密碼錯誤，或帳號尚未通過審核。",
    "header_create_account": "建立新帳號",
    "header_create": "建立帳號",
    "header_byok": "自備 API Key (必填)",
    "msg_byok_info": "本系統採 BYOK 模式，需自備 API Key。",
    "boyk_title": "⚠️ 本系統採用 BOYK (Bring Your Own Key) 模式",
    "boyk_desc": "為了使用 AI 改卷與出題功能，您必須提供自己的 LLM API Key (Google Gemini)。",
    "link_get_api_key_md": "👉 **[點此前往 Google AI Studio 取得免費 API Key](https://aistudio.google.com/app/apikey)**",
    "boyk_link_text": "👉 點此免費獲取 Google Gemini API Key",
    "lbl_google_api_key": "Google Gemini API Key *",
    "help_google_api_key": "以 'AIza' 開頭",
    "header_apikey": "API Key",
    "help_apikey": "Paste string starting with 'AIza'",
    "lbl_set_user": "設定帳號 (Username)*",
    "lbl_set_pwd": "設定密碼 (Password)*",
    "lbl_real_name": "真實姓名 (Real Name)*",
    "lbl_email": "Email*",
    "lbl_school": "學校 (School)*",
    "lbl_dept": "系所 (Dept)*",
    "err_pwd_mismatch": "密碼不一致",
    "err_all_required": "所有欄位皆為必填 (含 API Key)",
    "err_missing_api_key": "缺少 API Key",
    "err_username_dup": "使用者名稱已存在",
    "err_email_dup": "Email 已註冊",
    "err_reg_dup": "❌ 註冊失敗：該帳號或 Email 已被使用。",
    "err_missing_fields": "❌ 所有欄位（包含 API Key）皆為必填！",
    "err_reg_unknown": "❌ 註冊失敗：{}",
    "msg_reg_success": "✅ 註冊成功！請等待管理員審核通過後即可登入。",
    "msg_reg_fail": "註冊失敗",
    "msg_login_success": "登入成功",
    "msg_login_fail": "登入失敗",
    "plan_free_desc_fmt": "每日 {pages} 頁 • 基礎功能",
    "login_pricing_title": "選擇最適合您的方案",
    "plan_free_title": "🌱 免費版 (Free)",
    "plan_pro_title": "🚀 專業版 (Pro)",
    "plan_ent_title": "🏢 企業版 (Enterprise)",
    "price_free": "NT$ 0 / 月",
    "price_pro": "NT$ 990 / 月",
    "price_ent": "專屬報價",
    "feat_free_1": "每週 70 頁閱卷額度",
    "feat_free_2": "基礎 AI 分析",
    "feat_free_3": "標準客服支援",
    "feat_pro_1": "每週 500 頁閱卷額度",
    "feat_pro_2": "優先運算佇列 (5 Workers)",
    "feat_pro_3": "自訂試卷 Logo (Branding)",
    "feat_ent_1": "每週 2000 頁閱卷額度",
    "feat_ent_2": "極速運算 (12+ Workers)",
    "feat_ent_3": "專屬行銷 QR Code 導流",
    "feat_ent_4": "專屬客戶經理",
    "lbl_pricing_desc_free": "免費版描述",
    "lbl_pricing_desc_pro": "專業版描述",
    "lbl_pricing_desc_ent": "企業版描述",
    "ph_plan_price_free": "Free",
    "plan_free_desc": "基礎功能",
    "plan_pro_desc": "每週 500 頁",
    "plan_ent_desc": "每週 2000 頁",
    "login_footer_contact": "需要大量採購？請聯繫我們：sales@ai-grading.com",
    "footer_text": "Designed for University Mathematics Grading | Powered by Gemini",
    "support_btn_default_text": "支持我們",
    "support_tooltip_content": "您的貢獻將用於維護伺服器與開發新的 AI 數學工具。",
    "support_us": "感謝您的支持！",
    "pay_admin_header": "匯款審核（管理員）",
    "pay_admin_settings": "匯款資訊設定",
    "pay_admin_info_label": "匯款資訊（顯示於訂閱頁）",
    "pay_admin_info_help": "可輸入多行文字，支援 Markdown。",
    "pay_admin_save_info": "儲存匯款資訊",
    "pay_admin_info_updated": "匯款資訊已更新",
    "pay_admin_save_fail": "儲存失敗，請稍後再試",
    "pay_admin_list_caption": "待審核匯款清單",
    "pay_admin_no_pending": "目前沒有待審核的匯款",
    "col_id": "編號",
    "col_name": "姓名",
    "col_email": "Email",
    "col_plan": "方案",
    "col_amount": "金額",
    "col_last5": "帳號末五碼",
    "col_remitter": "匯款人",
    "col_time": "時間",
    "pay_admin_quick_review": "快速審核",
    "pay_admin_action_approve": "核准",
    "pay_admin_action_reject": "駁回",
    "pay_admin_confirm_btn": "確認",
    "pay_admin_err_select": "請先選擇一筆紀錄",
    "pay_admin_success_approved": "已核准：#{id} ({email})",
    "pay_admin_success_rejected": "已駁回：#{id}",
    "admin_title": "系統管理後台",
    "warn_admin_only": "權限不足：僅限管理員訪問",
    "admin_tab_stats": "系統概況",
    "admin_tab_users": "用戶管理",
    "admin_tab_config": "系統設定",
    "admin_tab_maintenance": "維護清理",
    "admin_stats_usage_title": "成本與用量分析",
    "admin_stats_total_cost": "總花費 (Total Cost)",
    "admin_stats_total_batches": "總閱卷批次",
    "admin_stats_user_rank": "用戶消耗排行",
    "admin_stats_no_data": "尚無使用紀錄",
    "admin_view_stats_error": "統計錯誤：{e}",
    "admin_stats_recent_billing": "近期批次帳單 (Recent Batches)",
    "admin_stats_no_billing": "無詳細帳單資料",
    "admin_view_billing_error": "帳務錯誤：{e}",
    "admin_user_mgmt_title": "用戶權限管理",
    "admin_no_data": "目前沒有資料",
    "admin_user_edit_status": "編輯用戶狀態",
    "admin_user_select_label": "選擇用戶 (Select User)",
    "admin_user_approved": "已核准 (Approved)",
    "admin_user_admin_role": "管理員 (Admin)",
    "admin_user_plan_label": "方案等級 (Plan)",
    "admin_view_text_001": "🎯 **個別用戶配額覆寫**",
    "admin_view_text_002": "💾 儲存用戶變動配額",
    "admin_view_text_003": "用戶 {username} 設定已更新！",
    "admin_config_global_title": "全域參數設定",
    "admin_config_quota_section": "配額管理",
    "admin_view_a_page_quota": "**A. 閱卷週頁數限制**",
    "admin_view_b_exam_gen_quota": "**B. 每週出卷份數限制**",
    "admin_marketing_title": "行銷與公告設定",
    "admin_cms_caption": "管理訂閱頁顯示文字",
    "lbl_promo_active": "啟用促銷橫幅",
    "lbl_promo_text": "促銷橫幅內容",
    "lbl_plan_title": "方案標題",
    "lbl_plan_price": "方案價格",
    "lbl_plan_desc": "方案介紹",
    "admin_view_branding_popover": "#### 🎨 品牌與側邊欄彈窗",
    "admin_config_donation_url": "頁腳連結 URL (Donation URL)",
    "admin_config_support_text": "頁腳按鈕文字 (Support Button Text)",
    "admin_config_support_popover": "頁腳 Popover 提示內容",
    "admin_config_ai_rules": "AI 全域規則 (Global AI Rules)",
    "admin_config_save_btn": "儲存所有設定",
    "admin_config_save_success": "系統設定已儲存",
    "admin_marketing_save": "儲存行銷設定",
    "admin_config_max_workers": "最大並發執行緒",
    "admin_maint_policy_expander": "設定保留策略",
    "admin_maint_policy_updated": "策略已更新",
    "admin_pending": "待審核用戶",
    "admin_user_mgmt": "用戶管理",
    "admin_user_update_btn": "更新用戶狀態",
    "admin_user_update_fail": "更新失敗",
    "admin_user_update_success": "用戶 {username} 更新成功！",
    "admin_maint_db_title": "資料庫維護",
    "admin_maint_retention_info": "目前的保留策略",
    "admin_maint_retention_days": "保留天數 (Days)",
    "admin_maint_update_policy_btn": "更新策略",
    "admin_view_policy_updated": "政策已更新",
    "admin_maint_cleanup_now": "立即執行清理",
    "warn_delete_batch": "⚠️ 警告：永久刪除此批次紀錄？",
    "admin_maint_cleanup_warn_zero": "取消操作",
    "admin_maint_cleaning_spinner": "正在清理過期資料...",
    "admin_maint_cleanup_done": "清理完成！移除 {count} 批次。",
    "sub_title": "訂閱方案",
    "sub_expired": "已到期",
    "sub_msg_expired": "您的方案 {plan} 已到期。",
    "sub_active": "使用中",
    "sub_status_info": "狀態：{status}｜到期日：{date}",
    "sub_free_label": "免費",
    "sub_current_plan": "目前方案：{plan}",
    "sub_upgrade_header": "升級方案",
    "sub_manual_payment_header": "人工匯款回報",
    "sub_manual_payment_caption": "填寫資訊後送出",
    "sub_bank_info_expander": "匯款資訊",
    "sub_plan_select": "選擇方案",
    "sub_amount_input": "匯款金額",
    "sub_remitter_input": "匯款人姓名",
    "sub_last5_input": "帳號末五碼",
    "sub_submit_btn": "送出回報",
    "sub_err_incomplete": "請填寫完整資訊",
    "sub_success_msg": "已送出，請等待審核。",
    "sub_err_system": "系統錯誤，請稍後再試。",
    "lbl_score_unit": "分",
    "gen_subject": "科目名稱",
    "lbl_total_score": "本題總分",
    "gen_dept": "系級/班級",
    "gen_exam_note": "考試注意事項",
    "lbl_time": "考試時間",
    "lbl_name": "姓名",
    "lbl_id": "學號",
    "lbl_seat": "座號",
    "lbl_grader": "閱卷人",
    "lbl_score_box": "實得分數",
    "lbl_calc_area": "計算區",
    "default_exam_note": "請詳細列出計算過程。",
    "page_label": "頁面",
    "ai_analysis_report": "AI 教學分析報告",
    "batch_id_label": "批次編號",
    "date_label": "日期",
    "statistics_overview": "班級成績統計概覽",
    "average_score": "平均分數",
    "pass_rate": "及格率",
    "question_analysis": "題目分析",
    "ai_insights_header": "AI 深度分析與建議",
    "step_1": "1. 設定標準",
    "step_2": "2. 執行閱卷",
    "step_3": "3. 結果報告",
    "subject_select": "選擇科目",
    "upload_rubric_label": "上傳 PDF",
    "ai_gen_rubric": "✨ AI 自動生成標準",
    "analyzing": "AI 分析中...",
    "edit_rubric_header": "編輯評分標準 (JSON)",
    "rubric_area_label": "評分標準內容",
    "save_next": "儲存並下一步",
    "prepare_rubric": "返回修改標準",
    "grading_settings": "閱卷參數設定",
    "grading_strategy": "閱卷策略",
    "mode_label": "嚴格模式",
    "report_mode": "報告詳細度",
    "upload_exam_label": "上傳學生考卷",
    "pps_label": "每位學生頁數",
    "split_btn": "✂️ 分割 PDF 並預覽",
    "splitting": "正在分割考卷...",
    "preview_chunks": "預覽分割結果",
    "start_grading_btn": "🚀 開始 AI 閱卷",
    "quota_exceeded_msg": "已超出配額",
    "no_results_yet": "尚無結果",
    "batch_complete": "批次完成",
    "median_score": "中位數",
    "pass_count": "及格人數",
    "gen_class_analysis_btn": "生成班級分析報告",
    "usage_header": "用量統計",
    "default_exam_title": "期中考試",
    "type_calc_normal": "一般計算題",
    "btn_load_draft": "📂 讀取草稿",
    "msg_no_drafts": "沒有找到任何草稿。",
    "lbl_select_exam": "選擇草稿",
    "btn_confirm_load": "📥 確認載入",
    "gen_header_info": "1. 試卷基本資訊",
    "lbl_category": "學院/類別",
    "lbl_new_cat_name": "新類別名稱",
    "gen_exam_title": "試卷主標題",
    "gen_exam_subtitle": "副標題",
    "btn_save_draft": "💾 儲存草稿",
    "msg_draft_saved": "草稿已儲存",
    "msg_save_failed": "儲存失敗",
    "lbl_latest": "最新",
    "gen_q_list": "2. 題目列表",
    "expander_import_bank": "➕ 從題庫匯入",
    "msg_bank_empty": "題庫為空",
    "lbl_select_questions": "選擇題目",
    "btn_add_selected_q": "加入選取的題目",
    "lbl_no_content": "尚未輸入內容",
    "expander_show_subs": "查看 {count} 個小題",
    "msg_no_questions": "目前尚無題目",
    "lbl_editing": "正在編輯",
    "gen_add_title": "3. 新增/編輯題目",
    "gen_content_label": "題目內容 (LaTeX)",
    "placeholder_q_content": "例如：試求極限...",
    "type_calc_large": "大型計算題",
    "type_choice": "選擇題",
    "type_proof": "證明題",
    "type_tf": "是非題",
    "type_fill": "填充題",
    "gen_type_label": "題型分類",
    "gen_height_label": "預留高度 (cm)",
    "mode_choice": "🔹 選擇題模式",
    "lbl_options": "選項列表",
    "placeholder_options": "A. 函數連續...",
    "gen_score_label": "配分",
    "gen_subs_check": "包含小題",
    "mode_composite": "🔹 複合題模式",
    "lbl_layout_cols": "小題排版 (欄數)",
    "lbl_sub_count": "小題數量",
    "lbl_sub_q": "小題內容",
    "lbl_score": "分數",
    "lbl_media": "插入媒體",
    "tab_upload_img": "上傳圖片",
    "tab_tikz": "TikZ 繪圖碼",
    "lbl_img_file": "選擇圖片檔案",
    "lbl_tikz_code": "TikZ LaTeX Code",
    "btn_update_q": "更新題目",
    "btn_add_q": "➕ 新增題目",
    "msg_q_updated": "題目已更新！",
    "msg_q_added": "題目已新增！",
    "btn_cancel_edit": "取消編輯",
    "header_gen_pdf": "3. 生成試卷預覽",
    "expander_latex_preview": "LaTeX 原始碼預覽",
    "lbl_source_code": "LaTeX 原始碼編輯",
    "btn_compile_manual": "手動編譯 LaTeX",
    "msg_compiling": "正在編譯 PDF...",
    "msg_compile_success": "編譯成功！",
    "msg_add_q_first": "請先新增題目",
    "remaining_quota_label": "剩餘配額",
    "btn_gen_pdf": "📄 生成 PDF 試卷",
    "msg_generating_pdf": "正在生成試卷...",
    "msg_gen_success": "試卷生成成功！",
    "btn_download_pdf": "📥 下載 PDF",
    "msg_no_criteria": "沒有評分標準",
    "header_cost_analysis": "成本分析",
    "lbl_total_tokens": "總 tokens",
    "lbl_sheet_count": "考卷份數",
    "lbl_model": "模型",
    "lbl_count": "數量",
    "chart_avg_score_by_q": "各題平均分數",
    "real_name": "真實姓名",
    "lbl_ai_thinking": "AI 思考",
    "lbl_questions_breakdown": "題目統計",
    "btn_view_rubric": "查看 Rubric",
    "msg_no_rubric_data": "沒有 Rubric 資料",
    "lbl_ai_analysis": "AI 分析",
    "msg_no_comment": "沒有評論",
    "lbl_grading_criteria": "評分標準",
    "btn_save_changes": "儲存變更",
    "msg_save_success": "儲存成功",
    "msg_no_details": "沒有詳情",
    "no_data": "尚無資料",
    "download_zip_btn": "下載完整報告包 (ZIP)",
    "delete_batch": "刪除批次",
    "status_failed": "失敗",
    "status_graded": "已閱",
    "header_class_stats": "班級統計",
    "lbl_student_count": "學生人數",
    "lbl_avg_score": "平均分數",
    "lbl_pass_rate": "及格率",
    "lbl_max_score": "最高分",
    "btn_view_charts": "查看圖表",
    "header_student_list": "學生清單",
    "lbl_search": "搜尋",
    "sort_id_asc": "學號（小→大）",
    "sort_id_desc": "學號（大→小）",
    "sort_score_desc": "分數（高→低）",
    "sort_score_asc": "分數（低→高）",
    "lbl_sort": "排序",
    "btn_show_subquestions": "顯示子題",
    "tab_bank_public": "🌏 公共題庫",
    "tab_bank_private": "🔒 私人題庫",
    "tab_bank_sets": "📂 我的題單",
    "tab_bank_add": "➕ 新增題目",
    "lbl_filters": "篩選條件",
    "lbl_chapter": "章節",
    "lbl_keyword": "關鍵字搜尋",
    "msg_cart_items": "🛒 暫存區題數",
    "btn_save_as_set": "💾 儲存為題單",
    "btn_confirm_save": "確認儲存",
    "msg_saved": "已儲存",
    "btn_clear_cart": "清除暫存",
    "msg_cart_empty": "暫存區是空的",
    "msg_no_data": "無符合條件題目",
    "btn_load_to_cart": "📥 載入暫存區",
    "header_add_new_q": "新增題目 (Contribution)",
    "err_json_format": "JSON 格式錯誤",
    "needs_review": "需要複核",
    "warn_no_batch_id": "找不到批次 ID",
    "back_step2": "返回上傳頁",
    "batch_id_info": "批次 ID: {}",
    "msg_all_reviewed": "全部已完成複核",
    "confidence_threshold": "信心門檻",
    "help_confidence_filter": "篩選需要人工複核答案",
    "review_pending_count": "待複核數",
    "select_record_to_review": "選擇要複核的紀錄",
    "student_id_label": "學號",
    "original_score_label": "原始分數",
    "preview_chunk_label": "預覽區塊",
    "err_file_not_found": "找不到檔案",
    "hilt_adjustment_header": "人工微調 (HITL)",
    "adjusted_score_label": "調整後分數",
    "comment_label": "評論",
    "save_btn": "儲存",
    "msg_review_saved": "複核已儲存",
    "err_save_exception": "儲存時發生錯誤",
    "ai_output_json_label": "AI 輸出 (JSON)",
    "profile_update_ok": "個人資料更新成功",
    "profile_update_fail": "更新失敗",
    "settings_title": "⚙️ 個人設定",
    "settings_profile_header": "基本資料",
    "change_pw_header": "修改密碼",
    "settings_memory_header": "AI 記憶庫",
    "theme_header": "介面主題",
    "email": "Email",
    "school": "學校",
    "department": "系所",
    "keys_header": "API 金鑰設定",
    "google_key": "Google Gemini Key",
    "openai_key": "OpenAI Key",
    "settings_branding_header": "🏢 品牌設定 (Premium)",
    "branding_caption": "設定 Logo 與 QR Code",
    "qr_url_label": "QR Code 連結",
    "upload_logo_label": "上傳 Logo",
    "branding_logo_help": "建議規格：300 DPI",
    "current_logo": "目前使用的 Logo",
    "upgrade_tip": "🔒 升級以解鎖品牌功能。",
    "save_profile": "儲存個人資料",
    "old_password": "舊密碼",
    "new_password": "新密碼",
    "new_password2": "確認新密碼",
    "change_password_btn": "更新密碼",
    "pw_empty": "密碼欄位不可為空",
    "pw_not_match": "兩次輸入不一致",
    "pw_update_ok": "密碼修改成功",
    "pw_update_fail": "密碼修改失敗",
    "ai_memory_header": "AI 評分規則記憶庫",
    "delete": "刪除",
    "mem_new_label": "新增規則",
    "settings_new_rule_placeholder": "例如：若只寫答案扣2分...",
    "add_rule": "加入規則",
    "add_ok": "規則已新增",
    "expander_add": "新增題目",
    "placeholder_content": "請輸入題目內容…",
    "val_q_new": "新",
    "msg_added": "已新增",
    "err_empty": "內容不可為空",
    "info_empty_bank": "題庫是空的",
    "lbl_select_edit": "選擇題目編輯",
    "header_edit": "編輯",
    "info_read_only": "題目 (唯讀)",
    "lbl_solution": "解答/解析",
    "help_solution": "支援 Markdown/LaTeX",
    "btn_update": "更新解答",
    "msg_updated": "已更新",
    "header_preview": "預覽",
    "caption_preview": "生成含解答 PDF",
    "btn_gen_preview": "生成預覽 PDF",
    "msg_generating": "生成中…",
    "err_gen_fail": "生成失敗",
}
